
create_ip -name pcie4c_uscale_plus -vendor xilinx.com -library ip -module_name pcie4c_uscale_plus_0

set_property -dict { 
  CONFIG.PL_LINK_CAP_MAX_LINK_SPEED {8.0_GT/s}
  CONFIG.PL_LINK_CAP_MAX_LINK_WIDTH {X16}
  CONFIG.AXISTEN_IF_EXT_512_CQ_STRADDLE {true}
  CONFIG.AXISTEN_IF_EXT_512_RQ_STRADDLE {true}
  CONFIG.AXISTEN_IF_EXT_512_RC_4TLP_STRADDLE {true}
  CONFIG.axisten_if_enable_client_tag {true}
  CONFIG.type1_membase_memlimit_enable {Disabled}
  CONFIG.type1_prefetchable_membase_memlimit {Disabled}
  CONFIG.PF0_CLASS_CODE {020000}
  CONFIG.PF0_DEVICE_ID {1001}
  CONFIG.PF0_MSIX_CAP_PBA_BIR {BAR_1:0}
  CONFIG.PF0_MSIX_CAP_PBA_OFFSET {00018000}
  CONFIG.PF0_MSIX_CAP_TABLE_BIR {BAR_1:0}
  CONFIG.PF0_MSIX_CAP_TABLE_OFFSET {00010000}
  CONFIG.PF0_MSIX_CAP_TABLE_SIZE {01F}
  CONFIG.PF0_REVISION_ID {00}
  CONFIG.PF0_SRIOV_CAP_INITIAL_VF {252}
  CONFIG.PF0_SRIOV_FIRST_VF_OFFSET {4}
  CONFIG.PF0_SUBSYSTEM_ID {9118}
  CONFIG.SRIOV_CAP_ENABLE {true}
  CONFIG.PF0_Use_Class_Code_Lookup_Assistant {false}
  CONFIG.PF0_SUBSYSTEM_VENDOR_ID {10ee}
  CONFIG.pf1_sriov_bar0_64bit {true}
  CONFIG.pf2_sriov_bar0_64bit {true}
  CONFIG.pf3_sriov_bar0_64bit {true}
  CONFIG.pf1_sriov_bar0_scale {Megabytes}
  CONFIG.pf1_sriov_bar0_prefetchable {true}
  CONFIG.pf0_sriov_bar0_size {16}
  CONFIG.pf0_bar0_enabled {true}
  CONFIG.pf0_bar0_type {Memory}
  CONFIG.pf0_bar0_64bit {true}
  CONFIG.pf0_bar0_prefetchable {true}
  CONFIG.pf0_bar0_scale {Megabytes}
  CONFIG.pf0_bar0_size {16}
  CONFIG.pf0_bar2_enabled {false}
  CONFIG.pf0_dev_cap_max_payload {1024_bytes}
  CONFIG.pf1_sriov_bar0_size {16}
  CONFIG.extended_tag_field {true}
  CONFIG.pf0_sriov_bar0_prefetchable {true}
  CONFIG.vendor_id {1234}
  CONFIG.pf0_ari_enabled {true}
  CONFIG.axisten_if_width {512_bit}
  CONFIG.pf0_sriov_bar0_64bit {true}
  CONFIG.pf0_msi_enabled {false}
  CONFIG.pf0_msix_enabled {true}
  CONFIG.pf0_sriov_bar0_scale {Megabytes}
  CONFIG.pf2_sriov_bar0_scale {Megabytes}
  CONFIG.pf2_sriov_bar0_prefetchable {true}
  CONFIG.pf2_sriov_bar0_size {16}
  CONFIG.pf3_sriov_bar0_scale {Megabytes}
  CONFIG.pf3_sriov_bar0_prefetchable {true}
  CONFIG.pf3_sriov_bar0_size {16}
  CONFIG.mode_selection {Advanced}
  CONFIG.axisten_freq {250}
  CONFIG.PL_DISABLE_LANE_REVERSAL {TRUE}
  CONFIG.MSI_X_OPTIONS {MSI-X_External}
} [get_ips pcie4c_uscale_plus_0]
